inherit_from: .rubocop_todo.yml

Layout/LineLength:
  Max: 99

Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - lib/tasks/auto_annotate_models.rake
    - db/schema.rb
    - config/initializers/simple_form_bootstrap.rb
